### 
GET http://localhost:3000

### search
GET http://localhost:3000/categories


### getOne
GET http://localhost:3000/categories/440dda2e-f109-4439-a2a3-f4f047d20914
Content-Type: application/json

### create
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Movie"
}

### update
PUT http://localhost:3000/categories/732f700b-51dc-4b99-8c67-85c7acb6d2f4
Content-Type: application/json

{
  "name": "Movie 1111ww"
}

### delete
DELETE  http://localhost:3000/categories/732f700b-51dc-4b99-8c67-85c7acb6d2f4
Content-Type: application/json
