### 
GET http://localhost:3000

### search
GET http://localhost:3000/categories


### getOne
GET http://localhost:3000/categories/e193bc2c-1b4f-4695-aab7-a162ac7d0017
Content-Type: application/json

### create
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Movie"
}

### update
PUT http://localhost:3000/categories/732f700b-51dc-4b99-8c67-85c7acb6d2f4
Content-Type: application/json

{
  "name": "Movie 1111ww"
}

### delete
DELETE  http://localhost:3000/categories/732f700b-51dc-4b99-8c67-85c7acb6d2f4
Content-Type: application/json
